/**
 * @file AuthRepository.js
 * @purpose Enterprise Data Layer for Firebase Authentication.
 * @responsibilities
 *  - Perform raw Firebase Authentication operations.
 *  - Catch and route all auth errors through ErrorHandler.
 *  - Provide a stable public API independent of Firebase SDK changes (v8 vs v9).
 * @collectionsUsed None
 * @cloudFunctionsUsed None (directly, relies on SDK)
 * @snapshotListeners onAuthStateChanged (must be cleaned up by consumers)
 * @transactions None
 * @publicAPI signInWithEmailAndPassword, signInWithCustomToken, signOut, onAuthStateChanged, getCurrentUser, getIdTokenResult
 * @futureMigrationPlan All files (e.g. AuthService, academy.js) must replace window.firebase.auth() and jhomeAuth with AuthRepository.
 */

import { FirebaseManager } from '../core/FirebaseManager.js';
import { ErrorHandler, AppError, ErrorCategory } from '../core/ErrorHandler.js';

export class AuthRepositoryClass {
    /**
     * Internal helper for standardized error reporting.
     * @private
     */
    _handleError(error, method) {
        const enhancedError = new AppError(
            error.message, 
            ErrorCategory.AUTHENTICATION, 
            error
        );
        ErrorHandler.handleError(enhancedError, `AuthRepository.${method}`);
        throw enhancedError;
    }

    /**
     * Sign in a user with email and password.
     * @param {string} email 
     * @param {string} password 
     * @returns {Promise<firebase.auth.UserCredential>}
     */
    async signInWithEmailAndPassword(email, password) {
        try {
            const auth = FirebaseManager.getAuth();
            return await auth.signInWithEmailAndPassword(email, password);
        } catch (error) {
            this._handleError(error, 'signInWithEmailAndPassword');
        }
    }

    /**
     * Sign in a user via a custom token generated by the backend.
     * @param {string} token 
     * @returns {Promise<firebase.auth.UserCredential>}
     */
    async signInWithCustomToken(token) {
        try {
            const auth = FirebaseManager.getAuth();
            return await auth.signInWithCustomToken(token);
        } catch (error) {
            this._handleError(error, 'signInWithCustomToken');
        }
    }

    /**
     * Sign out the current user.
     * @returns {Promise<void>}
     */
    async signOut() {
        try {
            const auth = FirebaseManager.getAuth();
            return await auth.signOut();
        } catch (error) {
            this._handleError(error, 'signOut');
        }
    }

    /**
     * Subscribe to authentication state changes.
     * @param {Function} callback (user) => void
     * @returns {Function} unsubscribe function to prevent memory leaks
     */
    onAuthStateChanged(callback) {
        try {
            const auth = FirebaseManager.getAuth();
            // In Firebase Compat, onAuthStateChanged returns an unsubscribe function.
            return auth.onAuthStateChanged(callback);
        } catch (error) {
            this._handleError(error, 'onAuthStateChanged');
        }
    }

    /**
     * Get the current synchronously available user.
     * @returns {firebase.auth.User | null}
     */
    getCurrentUser() {
        try {
            const auth = FirebaseManager.getAuth();
            return auth.currentUser;
        } catch (error) {
            this._handleError(error, 'getCurrentUser');
        }
    }

    /**
     * Fetch the ID Token result (including custom claims like permissions).
     * @param {boolean} forceRefresh 
     * @returns {Promise<firebase.auth.IdTokenResult>}
     */
    async getIdTokenResult(forceRefresh = false) {
        try {
            const auth = FirebaseManager.getAuth();
            if (!auth.currentUser) {
                throw new Error("No user is currently signed in.");
            }
            return await auth.currentUser.getIdTokenResult(forceRefresh);
        } catch (error) {
            this._handleError(error, 'getIdTokenResult');
        }
    }
}

export const AuthRepository = new AuthRepositoryClass();
